use std::collections::HashMap;
use serde_json::{json,Value};
use crate::formula;

const MAX_STEPS:usize=1_000_000;
pub fn execute(op:&str,args:&[Value])->Option<Result<Value,&'static str>>{if op.starts_with("ode."){Some(run(op,args))}else{None}}
fn run(op:&str,args:&[Value])->Result<Value,&'static str>{match op{
"ode.euler"=>fixed(args,0),"ode.heun"=>fixed(args,1),"ode.midpoint"=>fixed(args,2),"ode.rk4"=>fixed(args,4),"ode.rk45"=>rk45(args,false,false),"ode.rk45_trajectory"=>rk45(args,true,false),"ode.rk45_stats"=>rk45(args,false,true),
"ode.step_doubling_error"=>step_doubling(args),"ode.convergence_rk4"=>convergence(args),"ode.solve_grid"=>solve_grid(args),"ode.event_target"=>event_target(args),"ode.residual"=>residual(args),"ode.local_error_rk4"=>local_error(args),"ode.adaptive_reject_ratio"=>reject_ratio(args),"ode.compare_methods"=>compare_methods(args),_=>Err("OP")}}
fn num(v:&Value)->Result<f64,&'static str>{let x=v.as_f64().ok_or("TYPE")?;if x.is_finite(){Ok(x)}else{Err("NONFINITE")}}
fn expr(v:&Value)->Result<(&str,HashMap<String,f64>),&'static str>{let o=v.as_object().ok_or("TYPE")?;let e=o.get("e").and_then(Value::as_str).ok_or("ARG")?;let mut vars=HashMap::new();if let Some(m)=o.get("v"){for(k,v)in m.as_object().ok_or("TYPE")?{vars.insert(k.clone(),num(v)?);}}Ok((e,vars))}
fn f(e:&str,b:&HashMap<String,f64>,x:f64,y:f64)->Result<f64,&'static str>{let mut v=b.clone();v.insert("x".into(),x);v.insert("y".into(),y);formula::eval(e,&v)}
fn step(e:&str,b:&HashMap<String,f64>,x:f64,y:f64,h:f64,method:u8)->Result<f64,&'static str>{match method{0=>Ok(y+h*f(e,b,x,y)?),1=>{let k1=f(e,b,x,y)?;let k2=f(e,b,x+h,y+h*k1)?;Ok(y+h*(k1+k2)/2.0)},2=>{let k1=f(e,b,x,y)?;let k2=f(e,b,x+h/2.0,y+h*k1/2.0)?;Ok(y+h*k2)},4=>{let k1=f(e,b,x,y)?;let k2=f(e,b,x+h/2.0,y+h*k1/2.0)?;let k3=f(e,b,x+h/2.0,y+h*k2/2.0)?;let k4=f(e,b,x+h,y+h*k3)?;Ok(y+h*(k1+2.0*k2+2.0*k3+k4)/6.0)},_=>Err("OP")}}
fn fixed(args:&[Value],method:u8)->Result<Value,&'static str>{if args.len()!=5{return Err("ARG");}let(e,b)=expr(&args[0])?;let mut x=num(&args[1])?;let mut y=num(&args[2])?;let x1=num(&args[3])?;let n=args[4].as_u64().ok_or("TYPE")? as usize;if n==0||n>MAX_STEPS{return Err("LIMIT");}let h=(x1-x)/n as f64;for _ in 0..n{y=step(e,&b,x,y,h,method)?;x+=h;if !y.is_finite(){return Err("NONFINITE");}}Ok(json!({"x":x,"y":y,"steps":n}))}
fn dopri(e:&str,b:&HashMap<String,f64>,x:f64,y:f64,h:f64)->Result<(f64,f64),&'static str>{let k1=f(e,b,x,y)?;let k2=f(e,b,x+h/5.0,y+h*k1/5.0)?;let k3=f(e,b,x+3.0*h/10.0,y+h*(3.0*k1/40.0+9.0*k2/40.0))?;let k4=f(e,b,x+4.0*h/5.0,y+h*(44.0*k1/45.0-56.0*k2/15.0+32.0*k3/9.0))?;let k5=f(e,b,x+8.0*h/9.0,y+h*(19372.0*k1/6561.0-25360.0*k2/2187.0+64448.0*k3/6561.0-212.0*k4/729.0))?;let k6=f(e,b,x+h,y+h*(9017.0*k1/3168.0-355.0*k2/33.0+46732.0*k3/5247.0+49.0*k4/176.0-5103.0*k5/18656.0))?;let y5=y+h*(35.0*k1/384.0+500.0*k3/1113.0+125.0*k4/192.0-2187.0*k5/6784.0+11.0*k6/84.0);let k7=f(e,b,x+h,y5)?;let y4=y+h*(5179.0*k1/57600.0+7571.0*k3/16695.0+393.0*k4/640.0-92097.0*k5/339200.0+187.0*k6/2100.0+k7/40.0);Ok((y5,(y5-y4).abs()))}
fn rk45(args:&[Value],trajectory:bool,stats_only:bool)->Result<Value,&'static str>{if args.len()<4||args.len()>8{return Err("ARG");}let(e,b)=expr(&args[0])?;let mut x=num(&args[1])?;let mut y=num(&args[2])?;let x1=num(&args[3])?;let atol=if args.len()>4{num(&args[4])?}else{1e-9};let rtol=if args.len()>5{num(&args[5])?}else{1e-6};if atol<=0.0||rtol<=0.0{return Err("DOMAIN");}if x1==x{let obj=json!({"x":x,"y":y,"accepted":0,"rejected":0,"converged":true});return if trajectory{Ok(json!({"result":obj,"trajectory":[[x,y]]}))}else if stats_only{Ok(json!({"accepted":0,"rejected":0,"ratio":0.0}))}else{Ok(obj)};}let mut h=if args.len()>6{num(&args[6])?}else{(x1-x)/100.0};let max=if args.len()>7{args[7].as_u64().ok_or("TYPE")?.min(MAX_STEPS as u64)as usize}else{100_000};if h==0.0||max==0{return Err("DOMAIN");}let dir=if x1>=x{1.0}else{-1.0};h=h.abs()*dir;let mut accepted=0usize;let mut rejected=0usize;let mut pts=if trajectory{vec![json!([x,y])]}else{Vec::new()};for _ in 0..max{if (x1-x)*dir<=1e-15{let obj=json!({"x":x,"y":y,"accepted":accepted,"rejected":rejected,"converged":true});return if trajectory{Ok(json!({"result":obj,"trajectory":pts}))}else if stats_only{Ok(json!({"accepted":accepted,"rejected":rejected,"ratio":rejected as f64/(accepted+rejected).max(1) as f64}))}else{Ok(obj)};}if (x+h-x1)*dir>0.0{h=x1-x;}let(ynew,err)=dopri(e,&b,x,y,h)?;if !ynew.is_finite()||!err.is_finite(){return Err("NONFINITE");}let scale=atol+rtol*y.abs().max(ynew.abs());let ratio=if scale>0.0{err/scale}else{0.0};if ratio<=1.0{x+=h;y=ynew;accepted+=1;if trajectory{if pts.len()>=100_000{return Err("LIMIT");}pts.push(json!([x,y]));}}else{rejected+=1;}let factor=if ratio==0.0{5.0}else{(0.9*ratio.powf(-0.2)).clamp(0.2,5.0)};h*=factor;if !h.is_finite(){return Err("NONFINITE");}if h.abs()<1e-15{return Err("NO_CONVERGE");}}Err("NO_CONVERGE")}
fn step_doubling(args:&[Value])->Result<Value,&'static str>{if args.len()!=5{return Err("ARG");}let(e,b)=expr(&args[0])?;let x=num(&args[1])?;let y=num(&args[2])?;let h=num(&args[3])?;let method=args[4].as_u64().ok_or("TYPE")? as u8;if h==0.0{return Err("DIV0");}let y1=step(e,&b,x,y,h,method)?;let yh=step(e,&b,x,y,h/2.0,method)?;let y2=step(e,&b,x+h/2.0,yh,h/2.0,method)?;Ok(json!({"coarse":y1,"fine":y2,"error":(y2-y1).abs()}))}
fn convergence(args:&[Value])->Result<Value,&'static str>{if args.len()<5||args.len()>6{return Err("ARG");}let(e,b)=expr(&args[0])?;let x0=num(&args[1])?;let y0=num(&args[2])?;let x1=num(&args[3])?;let n=args[4].as_u64().ok_or("TYPE")? as usize;let levels=if args.len()==6{args[5].as_u64().ok_or("TYPE")? as usize}else{4};if n==0||!(3..=12).contains(&levels){return Err("LIMIT");}let mut vals=Vec::new();for l in 0..levels{let nn=n.checked_shl(l as u32).ok_or("LIMIT")?;if nn>MAX_STEPS{return Err("LIMIT");}let h=(x1-x0)/nn as f64;let mut x=x0;let mut y=y0;for _ in 0..nn{y=step(e,&b,x,y,h,4)?;x+=h;if !y.is_finite(){return Err("NONFINITE");}}vals.push(y);}let m=vals.len();let d1=(vals[m-2]-vals[m-3]).abs();let d2=(vals[m-1]-vals[m-2]).abs();let order=if d1>0.0&&d2>0.0{(d1/d2).log2()}else{f64::INFINITY};Ok(json!({"values":vals,"order":order,"delta":d2}))}
fn solve_grid(args:&[Value])->Result<Value,&'static str>{if args.len()!=4{return Err("ARG");}let(e,b)=expr(&args[0])?;let mut x=num(&args[1])?;let mut y=num(&args[2])?;let grid=args[3].as_array().ok_or("TYPE")?;const STEPS_PER_TARGET:usize=100;if grid.is_empty()||grid.len()>MAX_STEPS/STEPS_PER_TARGET{return Err("LIMIT");}let mut out=Vec::with_capacity(grid.len());for gx in grid{let target=num(gx)?;let h=(target-x)/STEPS_PER_TARGET as f64;for _ in 0..STEPS_PER_TARGET{y=step(e,&b,x,y,h,4)?;x+=h;if !y.is_finite(){return Err("NONFINITE");}}out.push(json!([x,y]));}Ok(json!(out))}
fn refine_target_event(e:&str,b:&HashMap<String,f64>,x:f64,y:f64,h:f64,target:f64,tol:f64)->Result<(f64,f64),&'static str>{let mut lo=0.0;let mut hi=h;let mut flo=y-target;let mut best=(x,y);for _ in 0..48{let mid=(lo+hi)/2.0;let ym=step(e,b,x,y,mid,4)?;let fm=ym-target;best=(x+mid,ym);if fm.abs()<=tol||((hi-lo).abs()<=tol.max(1e-12)){return Ok(best);}if fm*flo<=0.0{hi=mid;}else{lo=mid;flo=fm;}}Ok(best)}
fn event_target(args:&[Value])->Result<Value,&'static str>{if args.len()<5||args.len()>7{return Err("ARG");}let(e,b)=expr(&args[0])?;let mut x=num(&args[1])?;let mut y=num(&args[2])?;let x1=num(&args[3])?;let target=num(&args[4])?;let h=if args.len()>5{num(&args[5])?}else{if x1==x{1.0}else{(x1-x)/1000.0}};let tol=if args.len()>6{num(&args[6])?}else{1e-8};if h==0.0||tol<=0.0{return Err("DOMAIN");}if (y-target).abs()<=tol{return Ok(json!({"found":true,"x":x,"y":y}));}if x1==x{return Ok(json!({"found":false}));}let dir=if x1>=x{1.0}else{-1.0};let mut hh=h.abs()*dir;let mut prev=y-target;for _ in 0..MAX_STEPS{if (x1-x)*dir<=0.0{return Ok(json!({"found":false}));}if (x+hh-x1)*dir>0.0{hh=x1-x;}let yn=step(e,&b,x,y,hh,4)?;let cur=yn-target;if cur.abs()<=tol{return Ok(json!({"found":true,"x":x+hh,"y":yn}));}if cur*prev<0.0{let(ex,ey)=refine_target_event(e,&b,x,y,hh,target,tol)?;return Ok(json!({"found":true,"x":ex,"y":ey}));}x+=hh;y=yn;prev=cur;}Err("NO_CONVERGE")}
fn residual(args:&[Value])->Result<Value,&'static str>{if args.len()!=5{return Err("ARG");}let(e,b)=expr(&args[0])?;let x=num(&args[1])?;let y0=num(&args[2])?;let y1=num(&args[3])?;let h=num(&args[4])?;if h==0.0{return Err("DIV0");}Ok(json!(((y1-y0)/h-f(e,&b,x,y0)?).abs()))}
fn local_error(args:&[Value])->Result<Value,&'static str>{if args.len()!=4{return Err("ARG");}let(e,b)=expr(&args[0])?;let x=num(&args[1])?;let y=num(&args[2])?;let h=num(&args[3])?;if h==0.0{return Err("DIV0");}let y1=step(e,&b,x,y,h,4)?;let yh=step(e,&b,x,y,h/2.0,4)?;let y2=step(e,&b,x+h/2.0,yh,h/2.0,4)?;Ok(json!((y2-y1).abs()/15.0))}
fn reject_ratio(args:&[Value])->Result<Value,&'static str>{rk45(args,false,true)}
fn compare_methods(args:&[Value])->Result<Value,&'static str>{if args.len()!=5{return Err("ARG");}let(e,b)=expr(&args[0])?;let mut results=serde_json::Map::new();for(method,name)in[(0,"euler"),(1,"heun"),(2,"midpoint"),(4,"rk4")] {let mut x=num(&args[1])?;let mut y=num(&args[2])?;let x1=num(&args[3])?;let n=args[4].as_u64().ok_or("TYPE")? as usize;if n==0||n>MAX_STEPS{return Err("LIMIT");}let h=(x1-x)/n as f64;for _ in 0..n{y=step(e,&b,x,y,h,method)?;x+=h;}results.insert(name.into(),json!(y));}Ok(Value::Object(results))}
