use std::collections::HashMap;
use serde_json::{json,Value};
use crate::formula;

pub fn execute(op:&str,args:&[Value])->Option<Result<Value,&'static str>>{if op.starts_with("optimize."){Some(run(op,args))}else{None}}
fn run(op:&str,args:&[Value])->Result<Value,&'static str>{match op{
"optimize.golden_section"=>golden(args),"optimize.brent"=>brent(args),"optimize.bracket"=>bracket(args),"optimize.argmin_grid"=>argmin_grid(args),
"optimize.newton"=>newton(args),"optimize.gradient_descent1d"=>gd1(args),"optimize.gradient_descent2d"=>gd2(args),"optimize.nelder_mead2d"=>nelder2(args),
"optimize.coordinate_descent2d"=>coord2(args),"optimize.finite_diff_grad2d"=>grad2_op(args),"optimize.finite_diff_hessian2d"=>hess2_op(args),"optimize.armijo_step2d"=>armijo_op(args),
"optimize.bfgs2d"=>bfgs2(args),"optimize.line_search1d"=>line_search1d(args),"optimize.stationary_residual"=>stationary_residual(args),"optimize.audit_minimum"=>audit_min(args),_=>Err("OP")}}
fn num(v:&Value)->Result<f64,&'static str>{let x=v.as_f64().ok_or("TYPE")?;if x.is_finite(){Ok(x)}else{Err("NONFINITE")}}
fn expr(v:&Value)->Result<(&str,HashMap<String,f64>),&'static str>{let o=v.as_object().ok_or("TYPE")?;let e=o.get("e").and_then(Value::as_str).ok_or("ARG")?;let mut vars=HashMap::new();if let Some(m)=o.get("v"){for(k,v)in m.as_object().ok_or("TYPE")?{vars.insert(k.clone(),num(v)?);}}Ok((e,vars))}
fn f1(e:&str,b:&HashMap<String,f64>,x:f64)->Result<f64,&'static str>{let mut v=b.clone();v.insert("x".into(),x);formula::eval(e,&v)}
fn f2(e:&str,b:&HashMap<String,f64>,x:f64,y:f64)->Result<f64,&'static str>{let mut v=b.clone();v.insert("x".into(),x);v.insert("y".into(),y);formula::eval(e,&v)}
fn deriv(e:&str,b:&HashMap<String,f64>,x:f64,h:f64)->Result<f64,&'static str>{Ok((f1(e,b,x+h)?-f1(e,b,x-h)?)/(2.0*h))}
fn deriv2(e:&str,b:&HashMap<String,f64>,x:f64,h:f64)->Result<f64,&'static str>{Ok((f1(e,b,x+h)?-2.0*f1(e,b,x)?+f1(e,b,x-h)?)/(h*h))}
fn grad2(e:&str,b:&HashMap<String,f64>,x:f64,y:f64,h:f64)->Result<[f64;2],&'static str>{Ok([(f2(e,b,x+h,y)?-f2(e,b,x-h,y)?)/(2.0*h),(f2(e,b,x,y+h)?-f2(e,b,x,y-h)?)/(2.0*h)])}
fn finite(x:f64)->Result<Value,&'static str>{if x.is_finite(){Ok(json!(x))}else{Err("NONFINITE")}}
fn params1(args:&[Value],lo:usize)->Result<(f64,usize),&'static str>{let tol=if args.len()>lo{num(&args[lo])?}else{1e-9};let max=if args.len()>lo+1{args[lo+1].as_u64().ok_or("TYPE")?.min(100_000) as usize}else{1000};if tol<=0.0||max==0{return Err("DOMAIN");}Ok((tol,max))}
fn golden(args:&[Value])->Result<Value,&'static str>{if args.len()<3||args.len()>5{return Err("ARG");}let(e,b)=expr(&args[0])?;let(mut a,mut c)=(num(&args[1])?,num(&args[2])?);if a>=c{return Err("DOMAIN");}let(tol,max)=params1(args,3)?;let r=(5.0_f64.sqrt()-1.0)/2.0;let mut x1=c-r*(c-a);let mut x2=a+r*(c-a);let mut f1v=f1(e,&b,x1)?;let mut f2v=f1(e,&b,x2)?;let mut it=0;while(c-a).abs()>tol&&it<max{if f1v<f2v{c=x2;x2=x1;f2v=f1v;x1=c-r*(c-a);f1v=f1(e,&b,x1)?;}else{a=x1;x1=x2;f1v=f2v;x2=a+r*(c-a);f2v=f1(e,&b,x2)?;}it+=1;}let x=(a+c)/2.0;Ok(json!({"x":x,"fx":f1(e,&b,x)?,"iterations":it,"converged":(c-a).abs()<=tol}))}
fn brent(args:&[Value])->Result<Value,&'static str>{if args.len()<3||args.len()>5{return Err("ARG");}let(e,b)=expr(&args[0])?;let(mut a,mut c)=(num(&args[1])?,num(&args[2])?);if a>=c{return Err("DOMAIN");}let(tol,max)=params1(args,3)?;let mut x=a+0.3819660112501051*(c-a);let mut w=x;let mut v=x;let mut fx=f1(e,&b,x)?;let mut fw=fx;let mut fv=fx;let mut d=0.0f64;let mut ep=0.0f64;for it in 0..max{let m=0.5*(a+c);let tol1=tol*x.abs()+1e-14;let tol2=2.0*tol1;if (x-m).abs()<=tol2-0.5*(c-a){return Ok(json!({"x":x,"fx":fx,"iterations":it,"converged":true}));}let mut p=0.0;let mut q=0.0;let mut r=0.0;if ep.abs()>tol1{r=(x-w)*(fx-fv);q=(x-v)*(fx-fw);p=(x-v)*q-(x-w)*r;q=2.0*(q-r);if q>0.0{p=-p}else{q=-q}let et=ep;ep=d;if p.abs()<0.5*q*et.abs()&&p>q*(a-x)&&p<q*(c-x){d=p/q;let u=x+d;if u-a<tol2||c-u<tol2{d=if m-x>=0.0{tol1}else{-tol1};}}else{ep=if x>=m{a-x}else{c-x};d=0.3819660112501051*ep;}}else{ep=if x>=m{a-x}else{c-x};d=0.3819660112501051*ep;}let u=if d.abs()>=tol1{x+d}else{x+if d>0.0{tol1}else{-tol1}};let fu=f1(e,&b,u)?;if fu<=fx{if u>=x{a=x}else{c=x};v=w;fv=fw;w=x;fw=fx;x=u;fx=fu;}else{if u<x{a=u}else{c=u};if fu<=fw||w==x{v=w;fv=fw;w=u;fw=fu;}else if fu<=fv||v==x||v==w{v=u;fv=fu;}}}Err("NO_CONVERGE")}
fn bracket(args:&[Value])->Result<Value,&'static str>{if args.len()<2||args.len()>4{return Err("ARG");}let(e,b)=expr(&args[0])?;let x0=num(&args[1])?;let step=if args.len()>2{num(&args[2])?}else{1.0};let max=if args.len()>3{args[3].as_u64().ok_or("TYPE")?.min(1000) as usize}else{64};if step==0.0||max==0{return Err("DOMAIN");}let mut a=x0;let mut fa=f1(e,&b,a)?;let mut b0=x0+step;let mut fb=f1(e,&b,b0)?;let mut s=step;if fb>fa{s=-s;b0=x0+s;fb=f1(e,&b,b0)?;if fb>fa{let lo=x0-step.abs();let hi=x0+step.abs();return Ok(json!([lo,x0,hi]));}}for _ in 0..max{let c=b0+s*2.0;let fc=f1(e,&b,c)?;if fc>fb{return Ok(json!([a,b0,c]));}a=b0;fa=fb;b0=c;fb=fc;s*=2.0;if !fa.is_finite()||!s.is_finite(){return Err("NONFINITE");}}Err("NO_CONVERGE")}
fn argmin_grid(args:&[Value])->Result<Value,&'static str>{if args.len()!=4{return Err("ARG");}let(e,b)=expr(&args[0])?;let a=num(&args[1])?;let c=num(&args[2])?;let n=args[3].as_u64().ok_or("TYPE")? as usize;if n<2||n>1_000_000||a>=c{return Err("DOMAIN");}let mut bx=a;let mut bf=f1(e,&b,a)?;for i in 1..n{let x=a+(c-a)*i as f64/(n-1) as f64;let f=f1(e,&b,x)?;if f<bf{bf=f;bx=x;}}Ok(json!({"x":bx,"fx":bf}))}
fn newton(args:&[Value])->Result<Value,&'static str>{if args.len()<2||args.len()>5{return Err("ARG");}let(e,b)=expr(&args[0])?;let mut x=num(&args[1])?;let h=if args.len()>2{num(&args[2])?}else{1e-5};let tol=if args.len()>3{num(&args[3])?}else{1e-9};let max=if args.len()>4{args[4].as_u64().ok_or("TYPE")?.min(100_000)as usize}else{100};if h<=0.0||tol<=0.0||max==0{return Err("DOMAIN");}for it in 0..max{let g=deriv(e,&b,x,h)?;if g.abs()<=tol{return Ok(json!({"x":x,"fx":f1(e,&b,x)?,"grad":g,"iterations":it,"converged":true}));}let hh=deriv2(e,&b,x,h)?;if hh.abs()<1e-14{return Err("SINGULAR");}x-=g/hh;if !x.is_finite(){return Err("NONFINITE");}}Err("NO_CONVERGE")}
fn gd1(args:&[Value])->Result<Value,&'static str>{if args.len()<3||args.len()>6{return Err("ARG");}let(e,b)=expr(&args[0])?;let mut x=num(&args[1])?;let lr=num(&args[2])?;let h=if args.len()>3{num(&args[3])?}else{1e-5};let tol=if args.len()>4{num(&args[4])?}else{1e-8};let max=if args.len()>5{args[5].as_u64().ok_or("TYPE")?.min(100_000)as usize}else{10_000};if lr<=0.0||h<=0.0||tol<=0.0||max==0{return Err("DOMAIN");}for it in 0..max{let g=deriv(e,&b,x,h)?;if g.abs()<=tol{return Ok(json!({"x":x,"fx":f1(e,&b,x)?,"grad":g,"iterations":it,"converged":true}));}x-=lr*g;if !x.is_finite(){return Err("NONFINITE");}}Err("NO_CONVERGE")}
fn gd2(args:&[Value])->Result<Value,&'static str>{if args.len()<4||args.len()>7{return Err("ARG");}let(e,b)=expr(&args[0])?;let(mut x,mut y)=(num(&args[1])?,num(&args[2])?);let lr=num(&args[3])?;let h=if args.len()>4{num(&args[4])?}else{1e-5};let tol=if args.len()>5{num(&args[5])?}else{1e-8};let max=if args.len()>6{args[6].as_u64().ok_or("TYPE")?.min(100_000)as usize}else{10_000};if lr<=0.0||h<=0.0||tol<=0.0||max==0{return Err("DOMAIN");}for it in 0..max{let g=grad2(e,&b,x,y,h)?;let ng=g[0].hypot(g[1]);if ng<=tol{return Ok(json!({"x":[x,y],"fx":f2(e,&b,x,y)?,"grad_norm":ng,"iterations":it,"converged":true}));}x-=lr*g[0];y-=lr*g[1];if !x.is_finite()||!y.is_finite(){return Err("NONFINITE");}}Err("NO_CONVERGE")}
fn nelder2(args:&[Value])->Result<Value,&'static str>{if args.len()<3||args.len()>6{return Err("ARG");}let(e,b)=expr(&args[0])?;let x=num(&args[1])?;let y=num(&args[2])?;let step=if args.len()>3{num(&args[3])?}else{1.0};let tol=if args.len()>4{num(&args[4])?}else{1e-9};let max=if args.len()>5{args[5].as_u64().ok_or("TYPE")?.min(100_000)as usize}else{2000};if step<=0.0||tol<=0.0||max==0{return Err("DOMAIN");}let mut p=[[x,y],[x+step,y],[x,y+step]];for it in 0..max{p.sort_by(|a,c|f2(e,&b,a[0],a[1]).unwrap_or(f64::INFINITY).total_cmp(&f2(e,&b,c[0],c[1]).unwrap_or(f64::INFINITY)));let f0=f2(e,&b,p[0][0],p[0][1])?;let f2v=f2(e,&b,p[2][0],p[2][1])?;if (f2v-f0).abs()<=tol{return Ok(json!({"x":p[0],"fx":f0,"iterations":it,"converged":true}));}let c=[(p[0][0]+p[1][0])/2.0,(p[0][1]+p[1][1])/2.0];let r=[2.0*c[0]-p[2][0],2.0*c[1]-p[2][1]];let fr=f2(e,&b,r[0],r[1])?;let f1v=f2(e,&b,p[1][0],p[1][1])?;if fr<f0{let ex=[c[0]+2.0*(r[0]-c[0]),c[1]+2.0*(r[1]-c[1])];p[2]=if f2(e,&b,ex[0],ex[1])?<fr{ex}else{r};}else if fr<f1v{p[2]=r;}else{let co=[c[0]+0.5*(p[2][0]-c[0]),c[1]+0.5*(p[2][1]-c[1])];if f2(e,&b,co[0],co[1])?<f2v{p[2]=co;}else{p[1]=[(p[0][0]+p[1][0])/2.0,(p[0][1]+p[1][1])/2.0];p[2]=[(p[0][0]+p[2][0])/2.0,(p[0][1]+p[2][1])/2.0];}}}Err("NO_CONVERGE")}
fn coord2(args:&[Value])->Result<Value,&'static str>{if args.len()<3||args.len()>6{return Err("ARG");}let(e,b)=expr(&args[0])?;let(mut x,mut y)=(num(&args[1])?,num(&args[2])?);let span=if args.len()>3{num(&args[3])?}else{10.0};let tol=if args.len()>4{num(&args[4])?}else{1e-8};let max=if args.len()>5{args[5].as_u64().ok_or("TYPE")?.min(10_000)as usize}else{100};if span<=0.0||tol<=0.0||max==0{return Err("DOMAIN");}for it in 0..max{let ox=x;let oy=y;x=golden_x(e,&b,y,x-span,x+span,tol)?;y=golden_y(e,&b,x,y-span,y+span,tol)?;if (x-ox).hypot(y-oy)<=tol{return Ok(json!({"x":[x,y],"fx":f2(e,&b,x,y)?,"iterations":it+1,"converged":true}));}}Err("NO_CONVERGE")}
fn golden_x(e:&str,b:&HashMap<String,f64>,y:f64,mut a:f64,mut c:f64,tol:f64)->Result<f64,&'static str>{if tol<=0.0||a>=c{return Err("DOMAIN");}let r=0.6180339887498949;for _ in 0..256{if(c-a).abs()<=tol{return Ok((a+c)/2.0);}let x1=c-r*(c-a);let x2=a+r*(c-a);if f2(e,b,x1,y)?<f2(e,b,x2,y)?{c=x2}else{a=x1}}Err("NO_CONVERGE")}
fn golden_y(e:&str,b:&HashMap<String,f64>,x:f64,mut a:f64,mut c:f64,tol:f64)->Result<f64,&'static str>{if tol<=0.0||a>=c{return Err("DOMAIN");}let r=0.6180339887498949;for _ in 0..256{if(c-a).abs()<=tol{return Ok((a+c)/2.0);}let y1=c-r*(c-a);let y2=a+r*(c-a);if f2(e,b,x,y1)?<f2(e,b,x,y2)?{c=y2}else{a=y1}}Err("NO_CONVERGE")}
fn grad2_op(args:&[Value])->Result<Value,&'static str>{if args.len()<3||args.len()>4{return Err("ARG");}let(e,b)=expr(&args[0])?;let h=if args.len()==4{num(&args[3])?}else{1e-5};if h<=0.0{return Err("DOMAIN");}Ok(json!(grad2(e,&b,num(&args[1])?,num(&args[2])?,h)?))}
fn hess2_op(args:&[Value])->Result<Value,&'static str>{if args.len()<3||args.len()>4{return Err("ARG");}let(e,b)=expr(&args[0])?;let x=num(&args[1])?;let y=num(&args[2])?;let h=if args.len()==4{num(&args[3])?}else{1e-4};if h<=0.0{return Err("DOMAIN");}let f=f2(e,&b,x,y)?;let xx=(f2(e,&b,x+h,y)?-2.0*f+f2(e,&b,x-h,y)?)/(h*h);let yy=(f2(e,&b,x,y+h)?-2.0*f+f2(e,&b,x,y-h)?)/(h*h);let xy=(f2(e,&b,x+h,y+h)?-f2(e,&b,x+h,y-h)?-f2(e,&b,x-h,y+h)?+f2(e,&b,x-h,y-h)?)/(4.0*h*h);Ok(json!([[xx,xy],[xy,yy]]))}
fn armijo_op(args:&[Value])->Result<Value,&'static str>{if args.len()<5||args.len()>7{return Err("ARG");}let(e,b)=expr(&args[0])?;let x=num(&args[1])?;let y=num(&args[2])?;let dx=num(&args[3])?;let dy=num(&args[4])?;let c=if args.len()>5{num(&args[5])?}else{1e-4};let shrink=if args.len()>6{num(&args[6])?}else{0.5};if !(0.0<c&&c<1.0&&0.0<shrink&&shrink<1.0){return Err("DOMAIN");}let g=grad2(e,&b,x,y,1e-5)?;let f0=f2(e,&b,x,y)?;let slope=g[0]*dx+g[1]*dy;if slope>=0.0{return Err("DOMAIN");}let mut t=1.0;for _ in 0..64{if f2(e,&b,x+t*dx,y+t*dy)?<=f0+c*t*slope{return finite(t);}t*=shrink;}finite(0.0)}
fn bfgs2(args:&[Value])->Result<Value,&'static str>{if args.len()<3||args.len()>6{return Err("ARG");}let(e,b)=expr(&args[0])?;let(mut x,mut y)=(num(&args[1])?,num(&args[2])?);let tol=if args.len()>3{num(&args[3])?}else{1e-8};let max=if args.len()>4{args[4].as_u64().ok_or("TYPE")?.min(10_000)as usize}else{500};let hstep=if args.len()>5{num(&args[5])?}else{1e-5};if tol<=0.0||max==0||hstep<=0.0{return Err("DOMAIN");}let mut h=[[1.0,0.0],[0.0,1.0]];let mut g=grad2(e,&b,x,y,hstep)?;for it in 0..max{let ng=g[0].hypot(g[1]);if ng<=tol{return Ok(json!({"x":[x,y],"fx":f2(e,&b,x,y)?,"grad_norm":ng,"iterations":it,"converged":true}));}let d=[-(h[0][0]*g[0]+h[0][1]*g[1]),-(h[1][0]*g[0]+h[1][1]*g[1])];let t=armijo_scalar(e,&b,x,y,d,g)?;if t==0.0{return Err("NO_CONVERGE");}let s=[t*d[0],t*d[1]];let nx=x+s[0];let ny=y+s[1];if !nx.is_finite()||!ny.is_finite(){return Err("NONFINITE");}let ngv=grad2(e,&b,nx,ny,hstep)?;let q=[ngv[0]-g[0],ngv[1]-g[1]];let ys=q[0]*s[0]+q[1]*s[1];if ys>1e-14{let rho=1.0/ys;let a=[[1.0-rho*s[0]*q[0],-rho*s[0]*q[1]],[-rho*s[1]*q[0],1.0-rho*s[1]*q[1]]];let at=[[a[0][0],a[1][0]],[a[0][1],a[1][1]]];let ah=[[a[0][0]*h[0][0]+a[0][1]*h[1][0],a[0][0]*h[0][1]+a[0][1]*h[1][1]],[a[1][0]*h[0][0]+a[1][1]*h[1][0],a[1][0]*h[0][1]+a[1][1]*h[1][1]]];h=[[ah[0][0]*at[0][0]+ah[0][1]*at[1][0]+rho*s[0]*s[0],ah[0][0]*at[0][1]+ah[0][1]*at[1][1]+rho*s[0]*s[1]],[ah[1][0]*at[0][0]+ah[1][1]*at[1][0]+rho*s[1]*s[0],ah[1][0]*at[0][1]+ah[1][1]*at[1][1]+rho*s[1]*s[1]]];}x=nx;y=ny;g=ngv;}Err("NO_CONVERGE")}
fn armijo_scalar(e:&str,b:&HashMap<String,f64>,x:f64,y:f64,d:[f64;2],g:[f64;2])->Result<f64,&'static str>{let f0=f2(e,b,x,y)?;let slope=g[0]*d[0]+g[1]*d[1];if slope>=0.0{return Ok(0.0);}let mut t=1.0;for _ in 0..64{if f2(e,b,x+t*d[0],y+t*d[1])?<=f0+1e-4*t*slope{return Ok(t);}t*=0.5;}Ok(0.0)}
fn line_search1d(args:&[Value])->Result<Value,&'static str>{golden(args)}
fn stationary_residual(args:&[Value])->Result<Value,&'static str>{if args.len()<2||args.len()>3{return Err("ARG");}let(e,b)=expr(&args[0])?;let h=if args.len()==3{num(&args[2])?}else{1e-5};if h<=0.0{return Err("DOMAIN");}finite(deriv(e,&b,num(&args[1])?,h)?.abs())}
fn audit_min(args:&[Value])->Result<Value,&'static str>{if args.len()<2||args.len()>3{return Err("ARG");}let(e,b)=expr(&args[0])?;let x=num(&args[1])?;let h=if args.len()==3{num(&args[2])?}else{1e-4};if h<=0.0{return Err("DOMAIN");}let g=deriv(e,&b,x,h)?;let hh=deriv2(e,&b,x,h)?;Ok(json!({"fx":f1(e,&b,x)?,"grad":g,"curvature":hh,"stationary":g.abs()<=1e-6,"local_min":g.abs()<=1e-6&&hh>0.0}))}
