use std::collections::HashMap;
use serde_json::{json, Value};
use crate::formula;
use std::f64::consts::PI;

const MAX_SERIES: usize = 100_000;
const MAX_EULER_TERMS: usize = 4096;
const MAX_FOURIER_WORK: usize = 2_000_000;
const MAX_GEOMETRIC_N: u64 = 1_000_000;

pub fn execute(op: &str, args: &[Value]) -> Option<Result<Value, &'static str>> { if op.starts_with("series.") { Some(run(op,args)) } else { None } }
fn run(op:&str,args:&[Value])->Result<Value,&'static str>{match op{
"series.partial_sum"=>partial(args,false),"series.kahan_sum"=>partial(args,true),"series.convergence"=>convergence(args),"series.aitken"=>aitken(args),"series.richardson_limit"=>richardson(args),"series.euler_transform"=>euler_transform(args),
"series.geometric_sum"=>geometric(args),"series.power_eval"=>power_eval(args),"series.taylor_eval"=>power_eval(args),"series.taylor_exp"=>taylor_named(args,"exp"),"series.taylor_sin"=>taylor_named(args,"sin"),"series.taylor_cos"=>taylor_named(args,"cos"),
"series.fourier_coefficients"=>fourier_coeffs(args),"series.fourier_eval"=>fourier_eval(args),"series.chebyshev_coefficients"=>cheb_coeffs(args),"series.chebyshev_eval"=>cheb_eval(args),_=>Err("OP")}}
fn num(v:&Value)->Result<f64,&'static str>{let x=v.as_f64().ok_or("TYPE")?;if x.is_finite(){Ok(x)}else{Err("NONFINITE")}}
fn finite(x:f64)->Result<Value,&'static str>{if x.is_finite(){Ok(json!(x))}else{Err("NONFINITE")}}
fn vecf(v:&Value)->Result<Vec<f64>,&'static str>{let a=v.as_array().ok_or("TYPE")?;if a.len()>MAX_SERIES{return Err("LIMIT");}a.iter().map(num).collect()}
fn expr(v:&Value)->Result<(&str,HashMap<String,f64>),&'static str>{let o=v.as_object().ok_or("TYPE")?;let e=o.get("e").and_then(Value::as_str).ok_or("ARG")?;let mut vars=HashMap::new();if let Some(m)=o.get("v"){for(k,v)in m.as_object().ok_or("TYPE")?{vars.insert(k.clone(),num(v)?);}}Ok((e,vars))}
fn env_of(b:&HashMap<String,f64>)->formula::Env{formula::Env::new(b,&["x"])}
fn f1(env:&formula::Env,e:&str,x:f64)->Result<f64,&'static str>{env.set("x",x);env.eval(e)}
fn partial(args:&[Value],kahan:bool)->Result<Value,&'static str>{if args.len()!=1{return Err("ARG");}let xs=vecf(&args[0])?;let mut s=0.0;let mut c=0.0;if kahan{for x in xs{let y=x-c;let t=s+y;c=(t-s)-y;s=t;}}else{s=xs.iter().sum();}finite(s)}
fn convergence(args:&[Value])->Result<Value,&'static str>{if args.is_empty()||args.len()>3{return Err("ARG");}let xs=vecf(&args[0])?;if xs.len()<3{return Err("ARG");}let abs=if args.len()>1{num(&args[1])?}else{1e-9};let rel=if args.len()>2{num(&args[2])?}else{1e-6};if abs<0.0||rel<0.0{return Err("DOMAIN");}let n=xs.len();let d1=(xs[n-2]-xs[n-3]).abs();let d2=(xs[n-1]-xs[n-2]).abs();let scale=xs[n-1].abs().max(xs[n-2].abs());let ok=d2<=abs.max(rel*scale);let ratio=if d1>0.0{d2/d1}else{0.0};Ok(json!({"value":xs[n-1],"delta":d2,"ratio":ratio,"converged":ok}))}
fn aitken(args:&[Value])->Result<Value,&'static str>{if args.len()!=1{return Err("ARG");}let x=vecf(&args[0])?;if x.len()<3{return Err("ARG");}let n=x.len();let a=x[n-3];let b=x[n-2];let c=x[n-1];let d=c-2.0*b+a;if d.abs()<1e-15{return Err("SINGULAR");}finite(a-(b-a)*(b-a)/d)}
fn richardson(args:&[Value])->Result<Value,&'static str>{if args.len()!=3{return Err("ARG");}let coarse=num(&args[0])?;let fine=num(&args[1])?;let order=num(&args[2])?;if order<=0.0{return Err("DOMAIN");}let d=2.0_f64.powf(order)-1.0;if !d.is_finite()||d==0.0{return Err("DIV0");}finite(fine+(fine-coarse)/d)}
fn euler_transform(args:&[Value])->Result<Value,&'static str>{if args.len()!=1{return Err("ARG");}let mut a=vecf(&args[0])?;if a.is_empty(){return Err("EMPTY");}if a.len()>MAX_EULER_TERMS{return Err("LIMIT");}let mut sum=0.0;let mut factor=0.5;while !a.is_empty(){sum+=factor*a[0];if !sum.is_finite(){return Err("NONFINITE");}if a.len()==1{break;}a=a.windows(2).map(|w|w[0]-w[1]).collect();factor*=0.5;}finite(sum)}
fn geometric(args:&[Value])->Result<Value,&'static str>{if args.len()<2||args.len()>3{return Err("ARG");}let a=num(&args[0])?;let r=num(&args[1])?;if args.len()==2{if r.abs()>=1.0{return Err("DOMAIN");}return finite(a/(1.0-r));}let n=args[2].as_u64().ok_or("TYPE")?;if n>MAX_GEOMETRIC_N{return Err("LIMIT");}if (r-1.0).abs()<1e-15{finite(a*n as f64)}else{finite(a*(1.0-r.powi(n as i32))/(1.0-r))}}
fn power_eval(args:&[Value])->Result<Value,&'static str>{if args.len()<2||args.len()>3{return Err("ARG");}let c=vecf(&args[0])?;let x=num(&args[1])?;let center=if args.len()==3{num(&args[2])?}else{0.0};let z=x-center;let mut s=0.0;for &v in c.iter().rev(){s=s*z+v;if !s.is_finite(){return Err("NONFINITE");}}finite(s)}
fn taylor_named(args:&[Value],kind:&str)->Result<Value,&'static str>{if args.len()!=2{return Err("ARG");}let x=num(&args[0])?;let n=args[1].as_u64().ok_or("TYPE")? as usize;if n==0||n>200{return Err("LIMIT");}let mut sum=0.0;match kind{"exp"=>{let mut term=1.0;for k in 0..n{if k>0{term*=x/k as f64;}sum+=term;}},"sin"=>{let mut term=x;for k in 0..n{if k>0{term*=-x*x/((2*k) as f64*(2*k+1) as f64);}sum+=term;}},"cos"=>{let mut term=1.0;for k in 0..n{if k>0{term*=-x*x/((2*k-1) as f64*(2*k) as f64);}sum+=term;}},_=>return Err("OP")};finite(sum)}
fn fourier_coeffs(args:&[Value])->Result<Value,&'static str>{if args.len()<2||args.len()>3{return Err("ARG");}let y=vecf(&args[0])?;let k=args[1].as_u64().ok_or("TYPE")? as usize;let period=if args.len()==3{num(&args[2])?}else{2.0*PI};if period<=0.0{return Err("DOMAIN");}if y.len()<2||k>y.len()/2{return Err("SHAPE");}let n=y.len();let work=n.checked_mul(k+1).ok_or("LIMIT")?;if work>MAX_FOURIER_WORK{return Err("LIMIT");}let mut a=vec![0.0;k+1];let mut b=vec![0.0;k+1];for j in 0..=k{for(i,v)in y.iter().enumerate(){let th=2.0*PI*j as f64*i as f64/n as f64;a[j]+=v*th.cos();b[j]+=v*th.sin();}let endpoint=j==0||(n%2==0&&j==n/2);let scale=if endpoint{1.0/n as f64}else{2.0/n as f64};a[j]*=scale;b[j]*=scale;if endpoint{b[j]=0.0;}if !a[j].is_finite()||!b[j].is_finite(){return Err("NONFINITE");}}Ok(json!({"a":a,"b":b,"period":period}))}
fn fourier_eval(args:&[Value])->Result<Value,&'static str>{if args.len()!=2{return Err("ARG");}let o=args[0].as_object().ok_or("TYPE")?;let a=vecf(o.get("a").ok_or("ARG")?)?;let b=vecf(o.get("b").ok_or("ARG")?)?;if a.len()!=b.len()||a.is_empty(){return Err("SHAPE");}let period=o.get("period").map(num).transpose()?.unwrap_or(2.0*PI);if period<=0.0{return Err("DOMAIN");}let x=num(&args[1])?;let mut s=a[0];for k in 1..a.len(){let th=2.0*PI*k as f64*x/period;s+=a[k]*th.cos()+b[k]*th.sin();}finite(s)}
fn cheb_coeffs(args:&[Value])->Result<Value,&'static str>{if args.len()!=4{return Err("ARG");}let(e,b)=expr(&args[0])?;let env=env_of(&b);let lo=num(&args[1])?;let hi=num(&args[2])?;let n=args[3].as_u64().ok_or("TYPE")? as usize;if n==0||n>256||lo>=hi{return Err("DOMAIN");}let mut vals=vec![0.0;n];for(j,v)in vals.iter_mut().enumerate(){let t=(PI*(j as f64+0.5)/n as f64).cos();let x=(lo+hi)/2.0+(hi-lo)*t/2.0;*v=f1(&env,e,x)?;}let mut c=vec![0.0;n];for(k,ck)in c.iter_mut().enumerate(){for(j,v)in vals.iter().enumerate(){*ck+=v*(PI*k as f64*(j as f64+0.5)/n as f64).cos();}*ck*=2.0/n as f64;}c[0]*=0.5;if c.iter().any(|x|!x.is_finite()){return Err("NONFINITE");}Ok(json!({"c":c,"lo":lo,"hi":hi}))}
fn cheb_eval(args:&[Value])->Result<Value,&'static str>{if args.len()!=2{return Err("ARG");}let o=args[0].as_object().ok_or("TYPE")?;let c=vecf(o.get("c").ok_or("ARG")?)?;let lo=num(o.get("lo").ok_or("ARG")?)?;let hi=num(o.get("hi").ok_or("ARG")?)?;let x=num(&args[1])?;if lo>=hi{return Err("DOMAIN");}let t=(2.0*x-lo-hi)/(hi-lo);let mut b1=0.0;let mut b2=0.0;for &ck in c.iter().skip(1).rev(){let b0=2.0*t*b1-b2+ck;b2=b1;b1=b0;}finite(c[0]+t*b1-b2)}
